# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_use.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rapi_use.proto\" \n\x10UseCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1e\n\x10UseDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\t\",\n\x10UseUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1d\n\x0fUseQueryRequest\x12\n\n\x02id\x18\x01 \x01(\t\"*\n\x0eUseListRequest\x12\x18\n\x10latestCreateTime\x18\x01 \x01(\x03\"U\n\x11UseCommonResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ncreateTime\x18\x03 \x01(\x03\x12\x12\n\nupdateTime\x18\x04 \x01(\x03\"3\n\x0fUseListResponse\x12 \n\x04uses\x18\x01 \x03(\x0b\x32\x12.UseCommonResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_use_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USECREATEREQUEST']._serialized_start=17
  _globals['_USECREATEREQUEST']._serialized_end=49
  _globals['_USEDELETEREQUEST']._serialized_start=51
  _globals['_USEDELETEREQUEST']._serialized_end=81
  _globals['_USEUPDATEREQUEST']._serialized_start=83
  _globals['_USEUPDATEREQUEST']._serialized_end=127
  _globals['_USEQUERYREQUEST']._serialized_start=129
  _globals['_USEQUERYREQUEST']._serialized_end=158
  _globals['_USELISTREQUEST']._serialized_start=160
  _globals['_USELISTREQUEST']._serialized_end=202
  _globals['_USECOMMONRESPONSE']._serialized_start=204
  _globals['_USECOMMONRESPONSE']._serialized_end=289
  _globals['_USELISTRESPONSE']._serialized_start=291
  _globals['_USELISTRESPONSE']._serialized_end=342
# @@protoc_insertion_point(module_scope)
