# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61pi_user.proto\"!\n\x11UserCreateRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1f\n\x11UserDeleteRequest\x12\n\n\x02id\x18\x01 \x01(\t\"-\n\x11UserUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1e\n\x10UserQueryRequest\x12\n\n\x02id\x18\x01 \x01(\t\"+\n\x0fUserListRequest\x12\x18\n\x10latestCreateTime\x18\x01 \x01(\x03\"V\n\x12UserCommonResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ncreateTime\x18\x03 \x01(\x03\x12\x12\n\nupdateTime\x18\x04 \x01(\x03\"6\n\x10UserListResponse\x12\"\n\x05users\x18\x01 \x03(\x0b\x32\x13.UserCommonResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USERCREATEREQUEST']._serialized_start=18
  _globals['_USERCREATEREQUEST']._serialized_end=51
  _globals['_USERDELETEREQUEST']._serialized_start=53
  _globals['_USERDELETEREQUEST']._serialized_end=84
  _globals['_USERUPDATEREQUEST']._serialized_start=86
  _globals['_USERUPDATEREQUEST']._serialized_end=131
  _globals['_USERQUERYREQUEST']._serialized_start=133
  _globals['_USERQUERYREQUEST']._serialized_end=163
  _globals['_USERLISTREQUEST']._serialized_start=165
  _globals['_USERLISTREQUEST']._serialized_end=208
  _globals['_USERCOMMONRESPONSE']._serialized_start=210
  _globals['_USERCOMMONRESPONSE']._serialized_end=296
  _globals['_USERLISTRESPONSE']._serialized_start=298
  _globals['_USERLISTRESPONSE']._serialized_end=352
# @@protoc_insertion_point(module_scope)
